### PR TITLE
edited login page and instruction page 

### PR DESCRIPTION
**Pull request by Katy0903**
- The content in instruction page is a draft, will continue to finish tmr. 
- Maybe we can delete the loginsignup.html which I don't think we will use it, want to check with you before I delete it. 
- Thank you!

### CODE REVIEW

**Comment by MarcoCat** [comment]
Will merge when instructions page is complete. Reminder to keep styling in html css.

**Comment by Katy0903** [comment]
gotcha, thank for reminding!

**Comment by Katy0903** [comment]
- edited instruction page.
- added feedback html which we have pointed out in proposal that saying to get some thoughts from client, if we have time we can do this. It is not in app.py now.

**Review by MarcoCat — APPROVED** [review]
Looks good!

**Pull request merged**
